sonar.projectKey=aschott_anchor
sonar.organization=aschott
sonar.projectName=Anchor
sonar.projectVersion=0.0.1
sonar.sources=src
sonar.tests=tests
sonar.coverage.exclusions=**/Migrations/**,**/Program.cs,**/Startup.cs,**/*Tests*.cs,**/*Mock*.cs,**/anchor-*-template/**
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.exclusions=**/bin/**,**/obj/**,**/Migrations/**
